name: Build & Deploy
on: [ pull_request ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: |
          npm config set //npm.pkg.github.com/:_authToken $NODE_AUTH_TOKEN
          npm config set @navikt:registry=https://npm.pkg.github.com
          npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Build
        run: npm run build
      - name: Upload static files to NAV CDN
        uses: nais/deploy/actions/cdn-upload/v2@master
        with:
          team: medlemskap
          source: ./.next/static
          destination: "/_next"
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
      - name: Build and push docker image to GAR
        uses: nais/docker-build-push@main
        id: docker-push
        with:
          target: runtime
          team: medlemskap
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Deploy to nais
        uses: nais/deploy/actions/deploy@v2
        env:
          ENV: dev
          CLUSTER: dev-gcp
          IMAGE: ${{ steps.docker-push.outputs.image }}
          RESOURCE: config/nais-dev.yml
